export const POSITION_OPTIONS = [
    "Direksi",
    "VP/EVP",
    "Manager",
    "Staff",
];

export const UNIT_KERJA_OPTIONS = [
    "Accounting",
    "Assistant Designer",
    "Business Development",
    "Corporate Planning and Evaluation",
    "Corporate Secretary",
    "Dep - Assistant Designer",
    "Engineering",
    "Finance",
    "Finance and Human Capital",
    "General Affairs and HSSE",
    "Governance, Risk Management, Compliance and Management System",
    "Human Capital",
    "Information Systems",
    "Internal Control",
    "Logistics",
    "Marketing",
    "Marketing and Sales",
    "Product Development",
    "Production",
    "Project Installation and Maintenance",
    "Project Management",
    "Project Quality Control and Testing",
    "Quality Management",
    "Quality Management System",
    "Railway Signalling",
    "Railway Telecommunication and Electrification",
    "Research and Development",
    "Sales",
    "Sales Engineering",
    "Systems and Construction Engineering",
    "Technology and Operation",
];

export const JOB_TITLE_OPTIONS = [
    "Account Manager",
    "Accounting Manager",
    "Administration",
    "Administration Staff",
    "Application Information System Coordinator",
    "Assistant Designer",
    "Assistant Designer Coordinator",
    "Building Management",
    "Business Development Coordinator",
    "Chief Engineer",
    "Civil Engineer",
    "Civil Site Supervisor",
    "Cleaning Service",
    "Compensation and Benefit",
    "Controlling Account",
    "Corporate Legal and Contract Administration Coordinator",
    "Corporate Legal and License Staff",
    "Corporate Planning and Evaluation Manager",
    "Corporate secretary and Communication Management Coordinator",
    "Corporate Secretary Manager",
    "Deputy of Sales Vice President",
    "Director Secretary Staff",
    "Drafter Project",
    "Driver",
    "Employee Database Staff",
    "Engineering Administration Staff",
    "Engineering Executive Vice President",
    "Finance Manager",
    "Funding",
    "GA Administration Staff",
    "General Affairs and HSSE Manager",
    "General Journal",
    "Governance and Compliance Coordinator",
    "HC Administration and Document Control Staff",
    "HCGA Officer",
    "HCGS Administration Staff",
    "Health, Safety, Security and Environment (HSSE) Coordinator",
    "HSSE Officer",
    "HSSE Staff",
    "HSSE Supervisor",
    "Human Capital and General Support Vice President",
    "Human Capital Business Partner Coordinator",
    "Human Capital Management System Coordinator",
    "Human Capital Management System Staff",
    "Human Capital Manager",
    "Human Capital Operational and Services Staff",
    "Indoor Installation Coordinator",
    "Information Systems Manager",
    "Infrastructure Specialist",
    "Installation Technician",
    "Internal Control Manager",
    "Internal Verification",
    "IT Helpdesk",
    "IT Support",
    "Junior Account Manager",
    "Junior Budgeting Administration",
    "Junior Business Development staff",
    "Junior Chief Engineer",
    "Junior Contract Administration Staff",
    "Junior Corporate Evaluation and Budgeting Staff",
    "Junior Drafter Project",
    "Junior Financial Auditor",
    "Junior Internal Verification",
    "Junior Marketing and Sales Staff",
    "Junior Marketing staff",
    "Junior Production Planning Control Staff",
    "Junior Project Control",
    "Junior Project Interface Document Control",
    "Junior Project Planning and Evaluation",
    "Junior Project QC Engineer",
    "Junior Public Relation Staff",
    "Junior Quality Assurance Staff",
    "Junior Research and Development Staff",
    "Junior Risk Management Staff",
    "Junior Sales Engineer",
    "Junior Site Engineer",
    "Junior Site Manager",
    "Junior System Assurance",
    "Junior Testing Engineer",
    "Junior Tools Management Staff",
    "Logistics and Management System Administration Staff",
    "Logistics Control Staff",
    "Logistics Manager",
    "Logistics Planning",
    "Logistics Planning and Control Coordinator",
    "Logistics, Production and Quality Management Vice President",
    "Maintenance Supervisor",
    "Maintenance Technician",
    "Marketing and Business Development Vice President",
    "Marketing Manager",
    "Marketing staff",
    "Material Inspection",
    "Mechanical Design Coordinator",
    "Mechanical Designer",
    "Mechanical Senior Designer",
    "Operational Auditor",
    "Outdoor Installation Coordinator",
    "People Management Staff",
    "Performance and Reward Management Staff",
    "Plt. Direktur Keuangan and Sumber Daya Manusia",
    "Power and Substation Installation Coordinator",
    "Power Design Coordinator",
    "Power Designer",
    "Power Senior Designer",
    "Power Senior Principle Designer",
    "Procurement Coordinator",
    "Production Administration",
    "Production Document Control Staff",
    "Production Engineer",
    "Production Engineering and Management Coordinator",
    "Production Line Supervisor",
    "Production Maintenance Supervisor",
    "Production Manager",
    "Production Operation and Maintenance Coordinator",
    "Production Planning and Control Staff",
    "Production Quality Control Engineer",
    "Production Quality Control Inspector",
    "Production Technician",
    "Programmer",
    "Project Administration",
    "Project Administration Division Staff",
    "Project Control",
    "Project Design Document Control",
    "Project Document Control Coordinator",
    "Project Executive Vice President",
    "Project Installation and Maintenance Manager",
    "Project Interface Document Control",
    "Project Maintenance Administration Staff",
    "Project Maintenance Coordinator",
    "Project Maintenance Engineer Staff",
    "Project Maintenance Leader",
    "Project Maintenance Staff",
    "Project Management Manager",
    "Project Manager (Khusus)",
    "Project Manager A",
    "Project Manager B",
    "Project Manager C and D",
    "Project Planning and Evaluation",
    "Project Planning, Evaluation, and Control Coordinator",
    "Project QC Assistant",
    "Project QC Engineer",
    "Project Quality Control and Testing Manager",
    "Project Quality Control Coordinator",
    "Project Support and Industrial Relation",
    "Project Treasury Administration",
    "Public Relation",
    "Purchasing Staff",
    "QHSSE Management System Manager",
    "Quality Management System",
    "Quality Management System Coordinator",
    "Railway Signalling Manager",
    "Railway System Integrator",
    "Railway Telecommunication and Electrification Manager",
    "Receptionist",
    "Requirement Engineer",
    "Research and Development Manager",
    "Safety Man",
    "Sales Administration",
    "Sales Engineer",
    "Sales Engineering Manager",
    "Sales Manager",
    "Sales Staff",
    "Sekertaris Director Staff",
    "Senior Asset Management",
    "Senior Assistant Designer",
    "Senior Building Management",
    "Senior Chief Engineer",
    "Senior Corporate Planning Staff",
    "Senior Infrastructure Network Spesialist",
    "Senior Network Specialist",
    "Senior Product Development Principle Designer",
    "Senior Production Engineer",
    "Senior Project Administration",
    "Senior Project Control",
    "Senior Project Maintenance Staff",
    "Senior Project Planning and Evaluation",
    "Senior Quality Assurance Staff",
    "Senior Quality Management System",
    "Senior Train Control Principle Designer",
    "Senior Treasury",
    "Senior Vehicle",
    "Signalling High Level and HMI Software Designer",
    "Signalling High Level and HMI Software Senior Designer",
    "Signalling High Level, SCADA and HMI Software Design Coordinator",
    "Signalling Logic Software Design Coordinator",
    "Signalling Logic Software Designer",
    "Signalling Scheme and Circuit Design Coordinator",
    "Signalling Scheme and Circuit Designer",
    "Site Administration Manager",
    "Site Engineer",
    "Site Engineering Manager",
    "Site Operation Manager",
    "Site Project Document Control",
    "Site Supervisor Installation",
    "Site Warehouse Staff",
    "Staf Ahli Direktur Pemasaran and Penjualan",
    "Staf Ahli Direktur Pemasaran Dan Penjualan",
    "Staf Ahli Sipil",
    "Staff Ahli Direktur Keuangan and SDM",
    "Staff Ahli Direktur Teknologi and Operasi",
    "Supervisor Site Procurement Logistic and Equipment",
    "System Assurance",
    "System Assurance Coordinator",
    "System Integration Engineer",
    "Systems and Construction Engineering Coordinator",
    "Systems and Construction Engineering Manager",
    "Talent Management Staff",
    "Taxes Administration Staff",
    "Taxes Coordinator",
    "Telecommunication Design Coordinator",
    "Telecommunication Designer",
    "Telecommunication Senior Designer",
    "Testing Assistant",
    "Testing Engineer",
    "Testing Engineer Coordinator",
    "Tools Management Staff",
    "Train Control Design Coordinator",
    "Train Control Designer",
    "Train Control Principle Designer",
    "Treasury Administration",
    "Warehouse and Inventory Control",
    "Warehouse Coordinator",
];

export const STATUS_OPTIONS = [
    "Aktif",
    "Nonaktif",
];